apiVersion: v1
kind: Service
metadata:
  labels:
    app: application-service
  name: application-service
spec:
  type: NodePort
  ports:
    - port: 8889
      nodePort: 30094
  selector:
    app: application-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: application-service
  name: application-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: application-service
  template:
    metadata:
      labels:
        app: application-service
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "application-java"
        dapr.io/app-port: "8889"
        dapr.io/enable-api-logging: "true"
    spec:
      hostname: application-service
      containers:
        - env:
            - name: SPRING_PROFILES_ACTIVE
              value: k8s
          image: anhld17/app-dapr:1.1
          name: test-app
          ports:
            - containerPort: 8889