apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafdrop
  namespace: default
spec:
  selector:
    matchLabels:
      app: kafdrop
  replicas: 1
  template:
    metadata:
      labels:
        app: kafdrop
    spec:
      containers:
        - name: kafdrop
          image: obsidiandynamics/kafdrop:latest
          ports:
            - containerPort: 9000
          env:
            - name: KAFKA_BROKERCONNECT
              value: "kafka-broker-backup:9092"
            - name: JVM_OPTS
              value: "-Xms32M -Xmx64M"
---
apiVersion: v1
kind: Service
metadata:
  name: kafdrop-service
  namespace: default
spec:
  type: NodePort
  ports:
    - name: http
      port: 9000
      targetPort: 9000
      nodePort: 30191
  selector:
    app: kafdrop
