apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: storeredis
spec:
  type: state.redis # Sử dụng Redis làm state store
  version: v1
  metadata:
    - name: redisHost
      value: localhost:6379 # Địa chỉ Redis
    - name: enableTLS
      value: "false" # Sử dụng TLS hay không?
